Unit tests for the BooksController, BookService and BookRepository
theoterz/BookstoreApplication pull request #2
Opened 2024-06-12 07:22 UTC by theoterz

2024-06-16 12:02 UTC, panagiotispapa2000 requested changes
Well done. 
Observe the comments and apply them in relevant parts of the code.

2024-06-16 12:02 UTC, panagiotispapa2000 commented on src/test/java/com/bookstore/servicetests/BookServiceTests.java
> +    BookService bookService;
For unit test naming convention, you could name the class you are testing, as sut (system under test). This will indicate clearly the part where each method under test is being called in each test.
You could also have constructor dependency injection in a BeforeEach, instead of Autowiring

2024-06-16 12:02 UTC, panagiotispapa2000 commented on src/test/java/com/bookstore/servicetests/BookServiceTests.java
> +    void getBookByIdFailure() {
You can name this getBookByIdThrowsException. Same applies for the others.

2024-06-16 12:02 UTC, panagiotispapa2000 commented on src/test/java/com/bookstore/servicetests/BookServiceTests.java
> +        Optional<Book> mockBook = Optional.of(new Book(1, "Book Title", "Book Author",
It is convenient to define the type of objects as **var** instead of Optional<Book> and when you will mock it return an Optional.of(mockBook). Same thing applies for other tests.

2024-06-16 12:02 UTC, panagiotispapa2000 commented on src/test/java/com/bookstore/servicetests/BookServiceTests.java
> +        Optional<Book> mockBook = Optional.of(new Book(1, "Book Title", "Book Author",
No need for code duplication. You can define your most used objects in test class level, by adding them in a BeforeEach

2024-06-16 12:02 UTC, panagiotispapa2000 commented on src/test/java/com/bookstore/servicetests/BookServiceTests.java
> +        assertEquals(postBook.getIsbn(), returnedBook.getIsbn(), "The isbn values should be the same");
Also include Mockito verify assertions, to check whether each mocked repository or service is being called at least once. For example you want to verify getGenreById and then check if the mockGenre is equal to the desired one.

2024-06-16 12:02 UTC, panagiotispapa2000 commented on src/test/java/com/bookstore/servicetests/BookServiceTests.java
> +
You should also include the test for sut.getAllBooks for a combination of specification and paging alike

2024-06-16 12:02 UTC, panagiotispapa2000 commented on src/test/java/com/bookstore/servicetests/BookServiceTests.java
> +                bookService.getBookById(1));
You should also include the string error message related to _BOOK_NOT_FOUND_ as a third parameter in the assertThrows.

2024-06-16 12:02 UTC, panagiotispapa2000 commented on src/test/java/com/bookstore/servicetests/BookServiceTests.java
> +                bookService.getBookDTOById(1));
You should also include the string error message related to BOOK_NOT_FOUND as a third parameter in the assertThrows.

2024-06-16 12:02 UTC, panagiotispapa2000 commented on src/test/java/com/bookstore/servicetests/BookServiceTests.java
> +                bookService.createBook(postBook));
You should also include the string error message related to BOOK_ISBN_REGISTERED as a third parameter in the assertThrows.

2024-06-16 12:02 UTC, panagiotispapa2000 commented on src/test/java/com/bookstore/servicetests/BookServiceTests.java
> +                bookService.createBook(postBook));
You should also include the string error message related to GENRE_NOT_FOUND as a third parameter in the assertThrows.

2024-06-16 12:02 UTC, panagiotispapa2000 commented on src/test/java/com/bookstore/servicetests/BookServiceTests.java
> +                bookService.updateBook(putBook));
You should also include the string error message related to BOOK_NOT_FOUND as a third parameter in the assertThrows.

2024-06-16 12:02 UTC, panagiotispapa2000 commented on src/test/java/com/bookstore/servicetests/BookServiceTests.java
> +        doThrow(NoSuchElementException.class).when(genreService).getGenreById(100);
This mocking leads to false positive test.
You should mock the genreRepository findById instead.

2024-06-16 12:02 UTC, panagiotispapa2000 commented on src/test/java/com/bookstore/servicetests/BookServiceTests.java
> +    //Since the delete method is void and the deletion is always successful when the book exist, the successful execution is not tested
You should include the successful execution test.
You can create a Book object,
mock the behavior of existing id and after sut.deleteBook
you make an assertion via Mockito.verify(repository).deleteById
and also assertFalse(repository.existsById(#id))

2024-06-16 12:02 UTC, panagiotispapa2000 commented on src/test/java/com/bookstore/repositorytests/BookRepositoryTests.java
> +        Genre savedGenre = genreRepository.save(genre);
Is it necessary to make a seperated save for the savedGenre?
Isn't it saved afterwards, with bookRepository.save(book);

2024-06-16 12:02 UTC, panagiotispapa2000 commented on src/test/java/com/bookstore/controllertests/BooksControllerTests.java
> +
Make sure to add objects (postBook) in a BeforeEach to avoid duplication in seperated tests.

2024-07-02 10:55 UTC, AnastasiaTsav approved these changes

2024-07-02 13:29 UTC, merged